"""Write a PackResult out as Connect IQ resources + generated Monkey C."""

from __future__ import annotations

import base64
import json
import os
import shutil
from typing import Dict, List, Tuple

from .pack import EXTENT, FORMAT_VERSION, CLIP_BUFFER, PackOptions, PackResult

GENERATED_BANNER = """//
// GENERATED FILE -- DO NOT EDIT.
// Produced by tools/mappack. Re-run `make pack` to regenerate.
//
"""

#: Block indices are stored relative to each zoom's origin block, then packed
#: into one switch key as (relX << KEY_SHIFT) | relY. Absolute tile indices at
#: z16 reach 65535, which would not fit -- relative ones stay tiny.
KEY_SHIFT = 10
KEY_MAX = (1 << KEY_SHIFT) - 1


def resource_id(zoom: int, block_x: int, block_y: int) -> str:
    return "b%d_%d_%d" % (zoom, block_x, block_y)


def block_origins(result: PackResult) -> Dict[int, Tuple[int, int]]:
    """Top-left block index per zoom -- switch keys are stored relative to it."""
    origins: Dict[int, Tuple[int, int]] = {}
    for zoom, block_x, block_y in result.blocks:
        current = origins.get(zoom)
        if current is None:
            origins[zoom] = (block_x, block_y)
        else:
            origins[zoom] = (min(current[0], block_x), min(current[1], block_y))
    return origins


def write_pack(result: PackResult, options: PackOptions, out_dir: str,
               index_path: str, attribution: str) -> Dict[str, object]:
    blocks_dir = os.path.join(out_dir, "blocks")
    if os.path.isdir(blocks_dir):
        shutil.rmtree(blocks_dir)
    os.makedirs(blocks_dir, exist_ok=True)

    entries: List[Tuple[int, int, int, str, int, int]] = []
    total_binary = 0
    total_base64 = 0

    origins = block_origins(result)
    for (zoom, block_x, block_y), data in sorted(result.blocks.items()):
        origin_x, origin_y = origins[zoom]
        rel_x, rel_y = block_x - origin_x, block_y - origin_y
        if rel_x > KEY_MAX or rel_y > KEY_MAX:
            raise SystemExit(
                "pack spans %dx%d blocks at z%d, more than the %d limit -- "
                "shrink the bbox or drop the highest zoom"
                % (rel_x + 1, rel_y + 1, zoom, KEY_MAX + 1)
            )
        name = resource_id(zoom, block_x, block_y)
        encoded = base64.b64encode(data).decode("ascii")
        with open(os.path.join(blocks_dir, name + ".json"), "w", encoding="utf-8") as fh:
            json.dump([encoded], fh, separators=(",", ":"))
        entries.append((zoom, block_x, block_y, name, len(data), len(encoded)))
        total_binary += len(data)
        total_base64 += len(encoded)

    _write_resource_xml(out_dir, entries)
    _write_index(index_path, result, options, entries, attribution, total_binary)

    manifest = {
        "format_version": FORMAT_VERSION,
        "name": options.name,
        "attribution": attribution,
        "extent": EXTENT,
        "data_zooms": list(sorted(set(options.data_zooms))),
        "block_log2": {str(k): v for k, v in sorted(result.block_log2.items())},
        "bounds": list(result.bounds),
        "center": list(result.center),
        "tile_counts": {str(k): v for k, v in sorted(result.tile_counts.items())},
        "block_count": len(entries),
        "binary_bytes": total_binary,
        "base64_bytes": total_base64,
        "points_kept": result.total_points,
        "points_dropped": result.dropped_points,
    }
    with open(os.path.join(out_dir, "pack.json"), "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2, sort_keys=True)
        fh.write("\n")
    return manifest


def _write_resource_xml(out_dir: str, entries) -> None:
    lines = ['<resources>']
    lines.append('    <!-- GENERATED by tools/mappack. Do not edit. -->')
    for zoom, block_x, block_y, name, raw, enc in entries:
        lines.append(
            '    <jsonData id="%s" filename="blocks/%s.json" />  <!-- z%d %d/%d, %d B -->'
            % (name, name, zoom, block_x, block_y, raw)
        )
    lines.append('</resources>')
    lines.append('')
    with open(os.path.join(out_dir, "mapdata.xml"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def _write_index(path: str, result: PackResult, options: PackOptions, entries,
                 attribution: str, total_binary: int) -> None:
    data_zooms = sorted(set(options.data_zooms))
    origins = block_origins(result)
    by_zoom: Dict[int, List[Tuple[int, str]]] = {}
    for zoom, block_x, block_y, name, _raw, _enc in entries:
        origin_x, origin_y = origins[zoom]
        key = ((block_x - origin_x) << KEY_SHIFT) | (block_y - origin_y)
        by_zoom.setdefault(zoom, []).append((key, name))

    west, south, east, north = result.bounds
    center_lon, center_lat = result.center

    out: List[str] = [GENERATED_BANNER, "import Toybox.Lang;", "", "module MapIndex {"]
    out.append("    // --- format ---")
    out.append("    const FORMAT_VERSION = %d;" % FORMAT_VERSION)
    out.append("    const EXTENT = %d;" % EXTENT)
    out.append("    const CLIP_BUFFER = %d;" % CLIP_BUFFER)
    out.append("")
    out.append("    // --- this pack ---")
    out.append('    const PACK_NAME = "%s";' % options.name.replace('"', ""))
    out.append('    const ATTRIBUTION = "%s";' % attribution.replace('"', ""))
    out.append("    const MIN_ZOOM = %d;" % options.min_display_zoom)
    out.append("    const MAX_ZOOM = %d;" % options.max_display_zoom)
    out.append("    const DATA_ZOOMS = [%s];" % ", ".join(str(z) for z in data_zooms))
    out.append("    const BLOCK_LOG2 = [%s];"
               % ", ".join(str(result.block_log2.get(z, 3)) for z in data_zooms))
    out.append("    const BLOCK_ORIGIN_X = [%s];"
               % ", ".join(str(origins.get(z, (0, 0))[0]) for z in data_zooms))
    out.append("    const BLOCK_ORIGIN_Y = [%s];"
               % ", ".join(str(origins.get(z, (0, 0))[1]) for z in data_zooms))
    out.append("    const KEY_SHIFT = %d;" % KEY_SHIFT)
    out.append("")
    out.append("    const WEST = %.7fd;" % west)
    out.append("    const SOUTH = %.7fd;" % south)
    out.append("    const EAST = %.7fd;" % east)
    out.append("    const NORTH = %.7fd;" % north)
    out.append("    const CENTER_LON = %.7fd;" % center_lon)
    out.append("    const CENTER_LAT = %.7fd;" % center_lat)
    out.append("")
    out.append("    const BLOCK_COUNT = %d;" % len(entries))
    out.append("    const DATA_BYTES = %d;" % total_binary)
    out.append("")
    out.append("    //! Index of z in DATA_ZOOMS, or -1.")
    out.append("    function zoomSlot(z) {")
    out.append("        for (var i = 0; i < DATA_ZOOMS.size(); i += 1) {")
    out.append("            if (DATA_ZOOMS[i] == z) { return i; }")
    out.append("        }")
    out.append("        return -1;")
    out.append("    }")
    out.append("")
    out.append("    //! Best available data zoom for a display zoom.")
    out.append("    function dataZoomFor(displayZoom) {")
    out.append("        var best = DATA_ZOOMS[0];")
    out.append("        for (var i = 0; i < DATA_ZOOMS.size(); i += 1) {")
    out.append("            if (DATA_ZOOMS[i] <= displayZoom) { best = DATA_ZOOMS[i]; }")
    out.append("        }")
    out.append("        return best;")
    out.append("    }")
    out.append("")
    out.append("    //! Tiles per block axis, as a power of two, for a data zoom.")
    out.append("    function blockLog2(z) {")
    out.append("        var slot = zoomSlot(z);")
    out.append("        return slot < 0 ? BLOCK_LOG2[0] : BLOCK_LOG2[slot];")
    out.append("    }")
    out.append("")
    out.append("    //! Resource holding the block that owns (blockX, blockY) at zoom z,")
    out.append("    //! or null when nothing was packed there.")
    out.append("    function blockResource(z, blockX, blockY) {")
    out.append("        var slot = zoomSlot(z);")
    out.append("        if (slot < 0) { return null; }")
    out.append("        var rx = blockX - BLOCK_ORIGIN_X[slot];")
    out.append("        var ry = blockY - BLOCK_ORIGIN_Y[slot];")
    out.append("        if (rx < 0 || ry < 0 || rx > %d || ry > %d) { return null; }" % (KEY_MAX, KEY_MAX))
    out.append("        var key = (rx << KEY_SHIFT) | ry;")

    first = True
    for zoom in data_zooms:
        items = sorted(by_zoom.get(zoom, []))
        if not items:
            continue
        keyword = "if" if first else "} else if"
        first = False
        out.append("        %s (z == %d) {" % (keyword, zoom))
        out.append("            switch (key) {")
        for key, name in items:
            out.append("                case %d: return Rez.JsonData.%s;" % (key, name))
        out.append("            }")
    if not first:
        out.append("        }")
    out.append("        return null;")
    out.append("    }")
    out.append("}")
    out.append("")

    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
